name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dependencies audit
      id: audit
      run: yarn audit --groups dependencies --level high
    - name: Check for high vulnerabilities
      if: job.steps.audit.status > 90
      run: exit 1
